### ISSUE TITLE
RX marble testing

### ISSUE THREAD

**Issue by jhagai** [Sfeir/bouffe-front#105]
Une simple illustration de l'utilisation du marble testing (j'ai fait un petit projet angular avec plusieurs exemples du plus simple au plus complexe).

**Comment by Touffy** [comment]
Tu pourrais la faire quand ? le 31 mai ?

**Comment by parsyval** [comment]
Ca m'interesse, j'ai bô avoir fait la sfeirschool RxJS j'ai pas bien compris le marble testing

**Comment by jhagai** [comment]
Voici le lien vers le repo github de ma présentation:
https://github.com/jhagai/marble-testing

**Comment by Touffy** [comment]
Fait le 28 juin 2023
