### ISSUE TITLE
Les développeurs back-end le détestent : Découvrez comment ce fronteux se passe d'une api pour travailler

### ISSUE THREAD

**Issue by EreHuc** [Sfeir/bouffe-front#106]
### Description

```markdown
Que vous soyez dans l'avion, le train ou encore à Castelmoron-d’Albret on vous révèle tout les secrets pour pouvoir quand même developper ( livraison non incluse, faut pas déconner quand même ont peut pas pousser sans internet )
```

### Durée (minutes)

15-30

### À partir de

31/05/23

### Fait le 
29/06/23

### Support
https://github.com/EreHuc/bouffe-front

**Comment by SiegfriedEhret** [comment]
En attendant on attend.

**Comment by Touffy** [comment]
Fait le 28 juin 2023

**Comment by SiegfriedEhret** [comment]
@EreHuc tu as bien oublié de m'envoyer le lien pour y assister de loin.

**Comment by EreHuc** [comment]
:O Je t'ais complètement zapper :( Désolé 1000 fois avec les décalage & vacances ça met sortie de la tete :/

**Comment by SiegfriedEhret** [comment]
Ça a été enregistré ? Sinon t'es bon pour le refaire juste pour moi <3

**Comment by EreHuc** [comment]
Bonne question, après c'tai plus un rex sur ce que j'ai utiliser donc pas vraiment de support donc je peut te faire une version special Sieg :P
