### ISSUE TITLE
SystemJS Stargate SG-25

### ISSUE THREAD

**Issue by douglasduteil** [Sfeir/bouffe-front#12]
# SystemJS Stargate SG-25

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/730511/18369518/71934928-7626-11e6-91a6-2c92adc9dc56.png" alt="sg-25" width=248>
</p>

- Temps: 10min
- A partir de: Décembre

## Description

Introduction to SystemJS capacities to _require_ sources from all over the internet !
Live coding on plunker.

**Comment by olegskl** [comment]
Closing because it is really old.
