### ISSUE TITLE
lightening(vdm): When console.log({'e': 'what'}) is throwing error on "ctx.env.push"

### ISSUE THREAD

**Issue by douglasduteil** [Sfeir/bouffe-front#13]
# When console.log({'e': 'what'}) is throwing error on "ctx.env.push"
- Temps: 5-10 en minutes
- A partir de: Septembre
## Description

Mon super code de la mort qui tue de ya 1ans me retourne une vielle erreur genre  "Cannot read property 'push' of undefined on ctx.env.push" et la stack pointe sur la code base de node "util.js:601"
VDM

**Comment by olegskl** [comment]
Closing because it is really old.
