### ISSUE TITLE
Essayons d'être fonctionnel

### ISSUE THREAD

**Issue by florianorpeliere** [Sfeir/bouffe-front#15]
# Essayons d'être fonctionnel
- Temps: 30-45 minutes
- A partir de: Novembre
## Description

Le mot clé "fonctionnel" on l'entend partout et à toutes les sauces. Personnellement, j'adore la théorie et la vérité surtout :). Du coup, je vous propose de parler de fonctionnel en reprenant l'ensemble des concepts mathématiques afin de bien tout comprendre. 
Ne vous inquiétez pas, tout sera expliqué, pas besoin d'un niveau excellent en maths.

On verra bien si c'est juste map->filter->reduce ;) !

**Comment by olegskl** [comment]
Closing because it is really old.
