### ISSUE TITLE
Tiens, comment ça marche un navigateur ?

### ISSUE THREAD

**Issue by florianorpeliere** [Sfeir/bouffe-front#18]
# Tiens, comment ça marche un navigateur ?
- Temps: 45 minutes
- A partir de: Novembre
## Description

Surprise, mais vous l'aurez compris rapidement, on va voir ensemble comment un navigateur fonctionne.
Nous prendrons le cas de chromium pour répondre aux questions suivantes :
- Blink c'est quoi ? Comment ça marche ?
- V8 c'est quoi exactement ?
- Que fait chromium du coup ?

**Comment by olegskl** [comment]
Closing because it is really old.
