### ISSUE TITLE
Angular Universal 

### ISSUE THREAD

**Issue by manekinekko** [Sfeir/bouffe-front#2]
# Angular 2 Universal

Ce talk est une présentation du projet Angular 2 Universal. Universal est un module officiel d'Angular 2 permettant d'ajouter le support du server-rendering à vos web apps. En d'autres termes, avec Angular Universal il sera possible d'éxecuter une même application Angular 2 côté client et côté serveur. Avant, nous avions l'isomorphisme, avec Angular 2 nous avons l'universalisme. Si tu veux savoir comment Angular 2 gère l'universalité ne rate pas cette de session.

Temps : 30 (en minutes)

**Comment by olegskl** [comment]
Closing because it is really old.
