### ISSUE TITLE
Le WebRTC

### ISSUE THREAD

**Issue by ThomasCrevoisier** [Sfeir/bouffe-front#23]
# Le WebRTC

## Description

La techno a l'air cool, j'ai essayé de faire joujou avec mais impossible de trouver des ressources vraiment didactiques (coucou le [codelab](https://codelabs.developers.google.com/codelabs/webrtc-web/#0)).
Du coup si quelqu'un s'est déjà penché sur la question, ce serait top de montrer tout le potentiel de cette techno :)

**Comment by florianorpeliere** [comment]
Personne :'(
