### ISSUE TITLE
Tests e2e avec nightwatchjs

### ISSUE THREAD

**Issue by alexbrbr** [Sfeir/bouffe-front#24]
# Tests e2e avec nightwatchjs

- Temps: 20min
- A partir de: Février 2017

## Description

Une présentation de [nightwatchjs](http://nightwatchjs.org/), une libraire qui permet de faire tourner des tests e2e sur un serveur Selenium. 
Je vous ferai quelques démos, et ensuite une présentation de l'API pour montrer les possibilités (cliquer sur un élément, remplir des inputs, se connecter à un formulaire de login, vérifier que l'URL de la page est la bonne...).

**Comment by florianorpeliere** [comment]
Merci @alexbrbr !

**Comment by evanliomain** [comment]
@alexbrbr as-tu déjà rencontré [robot framework](http://robotframework.org/) dans tes recherches ?
Notre nouveau test manager en avait fait dans son ancienne boite. Les tests n'ont pas l'air trop compliqué à écrire, ce qui permettrait d'être écrit par un non développeur.
