### ISSUE TITLE
Présentation de gows

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/bouffe-front#3]
# gows

Temps: 20~30 minutes
A partir de: juillet

![go_lang_mascot_by_kirael_art-d7kunhu](https://cloud.githubusercontent.com/assets/537567/16121496/d43bf118-33e3-11e6-806a-7374dc84478e.gif)
## Description

Présentation d'un projet en [golang](https://golang.org/) pour jouer avec des repos git.

On reviendra sur quelques particularités de go, sur les difficultés que j'ai rencontrées.

**Comment by olegskl** [comment]
Je pense qu'on peut fermer cette issue, `NaN` ? 😄

**Comment by SiegfriedEhret** [comment]
Grave !

Siegfried Ehret
