### ISSUE TITLE
const bouffeFront = new Observable<BaconJS>() #29

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/bouffe-front#33]
# Bacon.js

![](https://baconjs.github.io/logo.png)

- Temps: comme tu voulez
- A partir de: comme tu voulez

## Description

Rx n'est pas le seul, il y a aussi [Bacon.js](https://baconjs.github.io/) !

Notes:

- En fait les prez Rx + Angular ça ne m'intéresse pas, je veux un truc sur le FRP et les Observables parce que je ne maîtrise pas le sujet. Le couplage à un framework, c'est annexe.
- Si c'est pour suivre les clics sur un bouton ça ne m'intéresse pas non plus, je veux des exemples où ça s'applique pour du vrai.

**Comment by SiegfriedEhret** [comment]
@Touffy mais mais mais ça a été fait ? Je veux des preuves !

**Comment by olegskl** [comment]
@Touffy C'est quand la prochaine Bouffe Front???

**Comment by Touffy** [comment]
Ha ! mon plan a fonctionné ! maintenant tu dois revenir dans le passé et faire cette présentation pour éviter un paradoxe temporel !

**Comment by Touffy** [comment]
@olegskl c'est le 28 juin. Vous êtes les bienvenus, évidemment.

**Comment by olegskl** [comment]
@Touffy Alright ! Je viens.

**Comment by SiegfriedEhret** [comment]
Vous faxez les pizzas pour ceux qui assistent en remote ?

**Comment by Touffy** [comment]
Non, sauf si tu te nourris de pur CSS. Par contre, y'a peut-être moyen de subventionner ton voyage à Paris si tu viens faire un talk (Cyril a pas dit non quand j'ai évoqué le sujet, au moins…).

**Comment by olegskl** [comment]
@Touffy c'est toi qui organize la Bouffe Front maintenant ? Ping moi si un jour tu veux faire une Code in the Dark chez SFEIR 😛

**Comment by Touffy** [comment]
Oui, c'est moi. Et bien sûr que je veux refaire des Code in the Dark !
