### ISSUE TITLE
Stratégie monorepo et Lerna

### ISSUE THREAD

**Issue by florianorpeliere** [Sfeir/bouffe-front#37]
# Stratégie monorepo et Lerna

- Temps: 30 minutes
- A partir de:  Avril

## Description
La strétégie monorepo est utilisée depuis 1999 par Google. Leurs équipes utilisent également le [trunk based development](https://trunkbaseddevelopment.com/). Nous allons faire le tour de ces deux concepts et je vais faire un retour d’expérience sur notre monorepo mis en place avec Lerna à la Société Générale.

- https://medium.com/@aboodman/in-march-2011-i-drafted-an-article-explaining-how-the-team-responsible-for-google-chrome-ships-c479ba623a1b#.t6rrlku65
- https://www.thoughtworks.com/insights/blog/enabling-trunk-based-development-deployment-pipelines

**Comment by douglasduteil** [comment]
Merci @olegskl :1st_place_medal:
