### ISSUE TITLE
Historisation des prez

### ISSUE THREAD

**Issue by ThomasCrevoisier** [Sfeir/bouffe-front#38]
Kikoo,

C'est pas une proposition, c'est pas une demande. Je soulève juste le fait qu'on enchaîne les bouffes front, les prez et qu'on n'en garde aucune trace.

Du coup est-ce que vous avez des idées pour régler le problème ? (un truc potentiellement cool serait de faire comme le meetup ParisJS qui a son site sur Github [ici](https://github.com/parisjs/parisjs-website), chaque speaker le fork, ajoute son talk et fait une PR).

Bisous

**Comment by ThomasCrevoisier** [comment]
Merci @florianorpeliere pour le setup de Travis ! 👏 🍾

**Comment by florianorpeliere** [comment]
Avec plaisir ! 🍾
