### ISSUE TITLE
beyond JavaScript

### ISSUE THREAD

**Issue by wolfgangGoedel** [Sfeir/bouffe-front#54]
# Beyond JavaScript

- Temps: 30 - 45 min
- A partir de: Juillet

## Description

Avec TypeScript ou Flow nous ajoutons une couche sémantique supplémentaire à notre code. A quoi ça sert ? Comment ça transforme notre perspective sur le développement ?

...et pourquoi aller plus loin (ou non) ?

Quelle valeur peuvent apporter des languages comme PureScript, Reason/OCaml ? Quel est le problème qu'ils prétendent résoudre ? ...et faut-il s'y intéresser ?

(cette présentation est fortement inspirée par le série de talk "taming the meta-language" de Cheng Lou (fb))

**Comment by florianorpeliere** [comment]
Merci @wolfgangGoedel !
