### ISSUE TITLE
Introducing the flux architecture in A2 with ngrx/store - The store as an observable of application state

### ISSUE THREAD

**Issue by techla** [Sfeir/bouffe-front#56]
# Introducing the flux architecture in Ax with ngrx/store - The store as an observable of application state

- Temps: ~ 30 (+/- 10) mins
- A partir de: fin juin.

## Description

Derrière l'emblématique Redux se cache une architecture nommée Flux dont l'application ne se limite pas qu'à React. Lors de cette présentation, je vous propose de découvrir ngrx/store, une implémentation de Flux pour Angular X basée sur les observables rxjs.

**Comment by florianorpeliere** [comment]
@techla Tu serais ok pour le 28 septembre ?

**Comment by techla** [comment]
Hello mister,


Ok pour le 28. Le format, c'est 20 min ?


________________________________
De : Florian Orpelière <notifications@github.com>
Envoyé : vendredi 1 septembre 2017 15:27
À : Sfeir/bouffe-front
Cc : techla; Mention
Objet : Re: [Sfeir/bouffe-front] Introducing the flux architecture in A2 with ngrx/store - The store as an observable of application state (#56)


@techla<https://github.com/techla> Tu serais ok pour le 28 septembre ?

**Comment by florianorpeliere** [comment]
@techla Super ! Tu peux avoir jusqu’à 30 minutes si tu souhaites.

**Comment by florianorpeliere** [comment]
Merci @techla
