### ISSUE TITLE
Webpack 101

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/bouffe-front#6]
# Titre
- Temps: 30 minutes (prez) ~ 1h (handson ?)
## Description

Webpack me semble un truc mystique, avec une configuration étrange et une documentation limite limite.

J'aimerai bien que quelqu'un nous explique tout ça.

**Comment by florianorpeliere** [comment]
tard+

**Comment by Kallikrein** [comment]
J'ai fait un let's talk tech sur webpack à la sogé, il a pas mal marché.
Si ça vous dit je suis tjs up !
