### ISSUE TITLE
Variables CSS / Custom Properties

### ISSUE THREAD

**Issue by Touffy** [Sfeir/bouffe-front#60]
# Variables CSS / Custom Properties

- Temps: 30 min
- À partir de: demain

## Description

Vous en avez entendu parler l'an dernier et vous vous êtes dit que vous étiez très bien avec votre préprocesseur CSS, du coup vous avez un peu oublié de tester cette petite merveille ?

Pour vous économiser l'effort de lire la spec, je vous présente les variables CSS (alias Custom Properties) en détail : comment ça s'écrit, quelles variétés de café ça sait faire, pourquoi c'est de la balle, et aussi les quelques faiblesses de la spec actuelle.

**Comment by florianorpeliere** [comment]
Merci pour la présentation 👍
