### ISSUE TITLE
Web Crypto API

### ISSUE THREAD

**Issue by Touffy** [Sfeir/bouffe-front#63]
# La cryptographie pour les <del>nuls</del> devs front qui n'ont pas envie de mettre 250ko de libs dans leur appli

- Temps: 45min
- À partir de: pas tout de suite

## Description

Une présentation parano où nous verrons comment vérifier la signature d'un JWT en quelques lignes, générer un secret partagé avec ECDH pour établir une connexion absolument pas protégée de l'abominable Homme du Milieu, et que la NSA a complètement infiltré le groupe de travail crypto du W3C.

**Comment by florianorpeliere** [comment]
Merci ! 👍

**Comment by alexbrbr** [comment]
https://sfeir.facebook.com/groups/189808334898587/permalink/203819633497457/
La vidéo a été publiée ici si vous voulez revoir ce talk
