### ISSUE TITLE
Monads

### ISSUE THREAD

**Issue by RudyWeber** [Sfeir/bouffe-front#64]
# Monads

- Temps: ±50min
- A partir de: Décembre

## Description

On en entend parler sans vraiment savoir ce que c'est. La plupart du temps les explications viennent de gens qui font ~du Haskell seuls dans des caves~ des maths et on lâche la conversation en 2 minutes parce qu'on nous explique de manière absolument limpide qu'avant il faut comprendre qu'en fait ça part juste d'un magma unifère, enfin un semi-groupe quoi, auquel on …. Ouais. Voilà. C'est chiant.
On va voir qu'en fait, comprendre les monads et leur intérêt sans avoir un PhD en théorie des catégories, c'est possible.

**Comment by florianorpeliere** [comment]
Merci ! 👍

**Comment by alexbrbr** [comment]
https://sfeir.facebook.com/groups/189808334898587/permalink/203819633497457/
La vidéo a été publiée ici si vous voulez revoir ce talk
