### ISSUE TITLE
VEGA : not just another chart library base on d3.js

### ISSUE THREAD

**Issue by evanliomain** [Sfeir/bouffe-front#65]
# VEGA : not just another chart library base on d3.js

- Temps: 30 min
- A partir de: Janvier

## Description

En dataviz, il y a une pléthore de librairie pour générer les camemberts et autres histogrammes. Mais on peut faire beaucoup mieux que ça. Et lorsque l'on pousse un peu, le nombre de librairie se restreint.

Lors de ce talk, je vous présenterai [vega](https://vega.github.io/), qui permet pratiquement de tout faire en matière de dataviz, à travers un live coding sur son [éditeur en ligne](https://vega.github.io/editor), avec des open data.

**Comment by gregorybarale** [comment]
+1

**Comment by evanliomain** [comment]
Le lien vers ma présentation : https://evanliomain.github.io/presentation_vega

Le lien vers le scénario que j'ai déroulé : https://github.com/evanliomain/presentation_vega/blob/master/spec/scenario3.md

Et sinon, tout est sur https://github.com/evanliomain/presentation_vega

**Comment by alexbrbr** [comment]
La vidéo du talk est disponible ici :
https://sfeir.facebook.com/groups/1968488280090607/permalink/2041792219426879/
