### ISSUE TITLE
Faire des PDFs avec du HTML/CSS et un Chrome headless

### ISSUE THREAD

**Issue by lgarnier** [Sfeir/bouffe-front#66]
# Faire des PDFs avec du HTML/CSS et un Chrome headless

- Temps: 30 minutes
- A partir de: quand je peux être présent à une bouffe front

## Description

Votre client veut faire un PDF à partir de la page web que vous avez faite ? Ça doit bien sûr être propre au niveau du rendu, passer sur tous les navigateurs, surtout IE, et évidemment couter le moins cher possible. Challenge accepted.

**Comment by florianorpeliere** [comment]
Merci :)
