### ISSUE TITLE
semver, loooooooool

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/bouffe-front#68]
# Titre

- Temps: 15 minutes
- A partir de: avril/mai

## Description

- Semantic Versioning, quoi c'est ? 
- Pourquoi c'est bien, ou pas ? On a quoi comme alternative ?
- Le tout en 15 minutes semi-troll histoire de rigoler un peu ! Hein ? Aller si, restez... :sweat_smile: 

![dontleave](https://user-images.githubusercontent.com/537567/36807142-66d80cb4-1cc2-11e8-9f10-8c1026150bfa.gif)

**Comment by alexbrbr** [comment]
Talk présenté à la bouffe front d'Avril !
Je rajouterai le lien de la vidéo quand dispo
