### ISSUE TITLE
Atomic Web Design

### ISSUE THREAD

**Issue by dahfazz** [Sfeir/bouffe-front#69]
# Atomic Web Design

- Temps: 45mn
- À partir de: Avril 2018

## Description

Une fois n'est pas coutume, un peu de CSS dans ce monde de barbares qui ne mettent plus de point virgules...

- Pour commencer, un peu de vocabulaire. Qu'est-ce qu'une Charte graphique ? qu'est-ce qu'un Design System ? 

- Rappel historique du travail réalisé sur le projet projet [DOCSSA](https://davidwalsh.name/deferred-objects-docssa)

- Présentation du fruit de la réflexion de [Brad Frost](http://bradfrost.com/blog/post/atomic-web-design/) qui introduit la notion de **Web Design Atomic**.

- Présentation de [Zeplin](https://zeplin.io/), essentiellement, voir en quoi il devient précieux lorsqu'on réfléchit en Atomic Design.

- Proposition personnelle d'implémentation en angular, mais applicable à toute stack.

- Pour conclure, quels sont vos feedbacks, expériences et propositions concernant le partage de composants graphiques dans une large organisation ?

**Comment by dahfazz** [comment]
Issue **69** 😚

**Comment by alexbrbr** [comment]
Le lien de la vidéo du talk est disponible ici : 
https://sfeir.facebook.com/groups/1968488280090607/permalink/2041792219426879/
