### ISSUE TITLE
Reason

### ISSUE THREAD

**Issue by olegskl** [Sfeir/bouffe-front#70]
# Reason

<img src="https://user-images.githubusercontent.com/298275/36973095-dc2c29e8-2071-11e8-9494-54f5462c4571.png" width="289" height="109">

- Temps: *comme tu veux*
- A partir de: *comme tu veux*

## Description

Ils veulent nous faire croire que *"Reason lets you write simple, fast and quality type safe code while leveraging both the JavaScript & OCaml ecosystems"*. Est-ce vrai ? Quelqu'un voudrait-il partager son experience avec cette langage ?

**Comment by SiegfriedEhret** [comment]
ping @RudyWeber et @wolfgangGoedel :smile:

**Comment by wolfgangGoedel** [comment]
Vous aurez votre petite intro ce soir - un peu de live coding, quelques slides...
...je propose aussi d'organiser un dojo fin juin - une soirée pour coder et découvrir en équipes - avec présentation des résultats à la fin.

**Comment by olegskl** [comment]
Done.
