### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by olegskl** [Sfeir/bouffe-front#71]
# WebAssembly

<img src="https://user-images.githubusercontent.com/298275/36973685-394882aa-2074-11e8-95cf-987acadc14cd.png" width="289px" height="152px">

- Temps: *comme tu veux*
- A partir de: *comme tu veux*

## Description

[WebAssembly](http://webassembly.org/) or wasm is a new portable, size- and load-time-efficient format suitable for compilation to the web.

**Comment by alexbrbr** [comment]
Je trouverais intéressant aussi de voir une utilisation de wasm en action avec du rust (via WebPack?!).
Ça peut faire plusieurs talks : 
- Présentation générale de wasm
- Utilisation de Rust
- Présentation de Rust
