### ISSUE TITLE
📘Storybook

### ISSUE THREAD

**Issue by cbellino** [Sfeir/bouffe-front#75]
# [Storybook](https://storybook.js.org/)

- Temps: 15-20min
- A partir de: Juin 2018

## Description

![Storybook logo](https://user-images.githubusercontent.com/622180/39568324-1e835644-4ec2-11e8-9947-5a428ae1fc5f.png)

Un environnement pour développer, tester, documenter et ajuster votre UI en isolation. 
L'idée est de créer un petit projet sandbox et de faire une live demo de l'outils :)

Quelques features que je peux démontrer:
- [x] Getting started.
- [x] Les bases (en react).
- [x] Knobs
- [x] Tests
- [x] Background
- [x] Déployer votre storybook avec travis + github.
- [x] Screenshots + diff + [https://percy.io/](percy) + [https://www.chromaticqa.com/](chromaticqa).

**Comment by cbellino** [comment]
Si vous êtes intéressés par des features particulières ou un intégration avec un autre outils, n'hésitez pas à proposer. Je vais essayer de faire un gros tour des features.

**Comment by evanliomain** [comment]
@cbellino Je serais assez intéressé de voir ce que l'on peut faire en matière de test avec le storybook.
Je sais qu'on peut le plugger à jest, mais j'aimerais voir son fonctionnement, et particulièrement les tests sur les diffs de screenshots de composant.

**Comment by cbellino** [comment]
@evanliomain Yes, c'est aussi quelque chose que j'aimerais explorer un peu car ça un moment que je n'ai pas regardé et ça a pas mal changé ces derniers temps :)

**Comment by olegskl** [comment]
Fait le 26 Septembre 2018. Merci @cbellino !
