### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by alexbrbr** [Sfeir/bouffe-front#78]
Si quelqu'un a de l'expérience sur React Native ça m'intéresserait de voir une prez dessus :)

**Comment by rchanaud** [comment]
Je travaille actuellement chez Meetic (Meetic Affinity) sur un projet monorepo en React (webapp mobile) et React Native (app native). L'archi a été montée par BAM, une boite spécialisée en React Native.
Comme ça ne fait qu'un mois que je suis sur React Native je n'ai pas encore assez de recul sur la techno mais je pourrai faire une présentation d'ici quelques mois.

**Comment by olegskl** [comment]
Done on 2019/04/30. Merci ! 😃
