### ISSUE TITLE
GraphQL - one endpoint to rule them all

### ISSUE THREAD

**Issue by wolfgangGoedel** [Sfeir/bouffe-front#80]
# GraphQL

- Temps: 30min
- A partir de: fin juillet

## Description

c'est un peu comme avec React - ça a mis un peu de temps pour arriver à maturité mais là ça y est - tout le monde en parle et on annonce déjà la mort des APIs REST...
(décidément notre profession à un certain goût pour le drame !

je vous donnerai un aperçu de la spec et de l'écosystème - on verra un peu de code - oui, juste un peu, parce que avec GraphQL il n'en faut pas plus ;)

**Comment by olegskl** [comment]
Done in July 2018. Thanks @wolfgangGoedel !
