### ISSUE TITLE
Des microservices en front avec Vue.js ! 

### ISSUE THREAD

**Issue by SiegfriedEhret** [Sfeir/bouffe-front#81]
# Une app multi-pages avec Vue.js ! 

- Temps: 15 minutes
- A partir de: maintenant

## Description

Si les composants sont des containers :whale:, le mode multi-pages c'est Kubernetes :truck:. 
Surfons :surfer: sur la vague de la hype des micro-services en l'appliquant à notre site ! :metal:

(:gift_heart: oui la description c'est n'importe quoi, mais c'est comme pour les confs, faut mettre des mots clés à la mode pour être pris).

**Comment by olegskl** [comment]
Il n'y a pas de #blockchain ni de #chatbot dans le descriptif de ta proposition, donc non, t'es pas pris !

**Comment by olegskl** [comment]
Fait à la Bouffe Front octobre 2018. Merci !
