### ISSUE TITLE
⚫ Cypress: E2E testing with sanity

### ISSUE THREAD

**Issue by cbellino** [Sfeir/bouffe-front#82]
# Titre

- Temps: 20-30min
- Le: 26 Février 2019

## Description

![Cypress](https://www.cypress.io/img/cypress-io-logo-social-share.png)
Cypress est un outil (test runner / application) qui permet de faire des tests E2E (End to End) et d'intégration avec un gros focus sur la rapidité (à la fois de développement et d'execution) et l'expérience développeurs (DX).

Je pense que beaucoup d'entre nous on déjà entendu parlé de Cypress mais que le sujet reste un peu flou pour pas mal.
J'ai quelques sujets en tête mais comme d'habitude si vous avez des points que vous voulez que j'approfondisse n'hésitez pas (debugging, CI, etc...) :)

## Au programme

- [ ] Getting started 🎉
- [ ] Writing a test (Live coding \o/) ✅
- [ ] Debugging with time travel ✨
- [ ] Hot reload ❤️
- [ ] Network mocks and utils 🌐
- [ ] Build on travis, gitlab, etc 👷‍♀️
- [ ] Artefacts 🌅
- [ ] Dashboard 📊
- [ ] Recorder 🎥

**Comment by evanliomain** [comment]
@cbellino, j'essai de pousser l'utilisation de cypress chez mon client (contre le traditionnel selenium). L'argument far pour selunium est qu'un non dev peux écrire un scénario via une extension Firefox qui enregistre la navigation et la convertie en script.
J'ai démonté cet avantage en 2s de recherche sur le store chrome en trouvant l'équivalent pour cypress.
Cela pourrait être intéressant d'en parler => https://chrome.google.com/webstore/detail/cypress-scenario-recorder/fmpgoobcionmfneadjapdabmjfkmfekb?hl=fr

Extension que je n'ai pas encore testé.

**Comment by cbellino** [comment]
Ah yes, c'est une feature que pas mal de gens attendent aussi, c'est dans le backlog chez cypress aussi: https://github.com/cypress-io/cypress/issues/73

**Comment by olegskl** [comment]
Fait le 28 mai 2019. Merci ❤️
