### ISSUE TITLE
Une bouffe Front des navigateurs

### ISSUE THREAD

**Issue by gregorybarale** [Sfeir/bouffe-front#83]
# La soirée des navigateurs

- Temps: TBD
- A partir de: TBD

## Description

Parce qu'au final, on travaille tout le temps avec, il serait intéressant de consacrer une soirée à nos navigateurs pour voir ce qui existe au delà des mastodontes usuels

L'idée initiale vient d'@olegskl

**Comment by dahfazz** [comment]
On pourra s'amuser à faire du debug IE5 ???

**Comment by gregorybarale** [comment]
Moi je pourrais faire un focus sur Brave
Parce qu'il y a ce monsieur dans le projet:
![image](https://user-images.githubusercontent.com/6875837/46199678-ed6bf080-c30f-11e8-88f5-717a9316e23f.png)

**Comment by douglasduteil** [comment]
Et moi, **Opera** 

<img src=https://user-images.githubusercontent.com/730511/46347881-5ffd0900-c64d-11e8-96d7-937470202457.gif width=693 />

**Comment by olegskl** [comment]
Soyons prêts pour le **27 novembre**! :)

**Comment by douglasduteil** [comment]
.

Je serai pas là le 27

Le mer. 24 oct. 2018 à 15:46, Oleg Sklyanchuk <notifications@github.com> a
écrit :

**Comment by EreHuc** [comment]
Pour moi ça sera **Vivaldi** !!

![image](https://media.giphy.com/media/iLsDDqQYZJWpy/giphy.gif)

**Comment by RudyWeber** [comment]
Je peux parler de Lynx :).

**Comment by olegskl** [comment]
Fait le 27 novembre 2018. Merci à tous les participants ! ❤️
