### ISSUE TITLE
React Hooks

### ISSUE THREAD

**Issue by olegskl** [Sfeir/bouffe-front#85]
# [React Hooks](https://reactjs.org/docs/hooks-intro.html)

- Temps: 15-30min
- A partir de: (quand veux-tu présenter ?)

## Description

React has announced Hooks in the upcoming v16.7. Has anyone tried them yet? Would like to have your thoughts and ideas.

**Comment by RudyWeber** [comment]
Je veux bien en parler :).

Le dim. 28 oct. 2018 à 14:52, Oleg Sklyanchuk <notifications@github.com> a
écrit :

**Comment by olegskl** [comment]
Fait par @RudyWeber le 18 décembre. Merci ! :)
