### ISSUE TITLE
Présentation de xLayers

### ISSUE THREAD

**Issue by gregorybarale** [Sfeir/bouffe-front#92]
# Présentation de xLayers

- Temps: _TBD_
- A partir de: _TBD_

## Description

Petite présentation de l'application xLayers qui pourrait bouleverser nos vies de développeurs Front et portée la l'OSPO de Sfeir.
Es-tu intéressé @manekinekko ?

[Lien du site de l'application](https://xlayers.app/#/home)

**Comment by manekinekko** [comment]
Avec plaisir. Comment procède-t-on?

**Comment by gregorybarale** [comment]
Yeah \o/. Il suffit juste de voir combien de temps serait nécessaire pour la présentation et de voir avec @olegskl et @alexbrbr quand un créneau se libère

**Comment by manekinekko** [comment]
Je suis dispos les Mercredi et Jeudi en Mars.
Ping @olegskl et @alexbrbr c'est quoi les prochaines dates ?

**Comment by alexbrbr** [comment]
La date n'est pas encore confirmée, je pense que pour le mois de Mars le planning est complet.

En général c'est le dernier mardi du mois à partir de 19h.
Donc mardi 30 Avril ou mardi 28 Mai par exemple, en fonction de tes dispos, du temps qu'il te faut pour préparer et des autres talks/speakers.

**Comment by manekinekko** [comment]
Le talk est deja prêt car je presente xLayers ce soir sur [Angular Air](https://www.youtube.com/watch?v=sBJuTMBkcfA).

Bon, pour les dispos, c'est mort alors. Les Mardis je ne suis pas dispo.

**Comment by manekinekko** [comment]
Eventuellement, si @Shikanime veut présenter le projet, ca me va.

**Comment by manekinekko** [comment]
@alexbrbr peux-tu affecter la tache à @Shikanime stp?

**Comment by alexbrbr** [comment]
Je ne peux pas l'affecter pour l'instant car pas dans l'organisation Sfeir sur GitHub (mais j'ai fait la demande à Cyril qui a les droits ça devrait pas tarder).
Merci à vous deux et bonne présentation ce soir 😄

**Comment by alexbrbr** [comment]
Fait par @Shikanime à la bouffe front du 28 Mars, merci à lui 👍 
Je ferme l'issue
