### ISSUE TITLE
V8 Internals: Arrays

### ISSUE THREAD

**Issue by OussamaRomdhane** [Sfeir/bouffe-front#93]
# V8 Internals: Arrays

- Temps: 20 à 30 minutes
- A partir de: mi-Juin

## Description

How are arrays treated internally in the V8 javascript engine? (We can do objects and primitive types etc later on, maybe even cover SpiderMonkey internals).
This is hugely inspired by Mathias Bynens' talk V8 internals for JavaScript developers (available [on youtube](https://www.youtube.com/watch?v=m9cTaYI95Zc)) + optimizations and other subjects from the V8 blog.

- Elements kinds
- Optimizations
- Packed vs Holey arrays
etc ...

**Comment by olegskl** [comment]
Fait le 29 octobre 2019. Merci !
