### ISSUE TITLE
Javascript types under the hood

### ISSUE THREAD

**Issue by evanliomain** [Sfeir/bouffe-front#94]
# Javascript types under the hood

- Temps: (~20 minutes)
- A partir de: mars

## Description

Les types en javascript, ça existe.

Quels sont leurs propriétés ?
Comment == fonctionne ?
Qu'es-ce qu'un Symbol et comment les utiliser ?

**Comment by evanliomain** [comment]
Vous pourrez voir ou revoir mes slides [ici](https://docs.google.com/presentation/d/e/2PACX-1vRkfln6KczKebpeyBhjH94mR1-_NuVpiheT7SF_vKag3GrkeuEdKsx11QWNX9zKXKaWpGg0bh0tF3Fj/pub?start=false&loop=false&delayms=60000).

**Comment by olegskl** [comment]
Fait le 29 octobre 2019. Merci !
