### ISSUE TITLE
Tout ce que vous n'avez jamais voulu savoir sur `with`

### ISSUE THREAD

**Issue by Touffy** [Sfeir/bouffe-front#98]
- Temps: 10 minutes
- À partir de: Date.now()

## Description

Le mot le plus haï de JavaScript, au point qu'il est tabou en _strict mode_… vous n'avez jamais voulu même en entendre parler, bah tant pis ! Je vous explique ce qui se passe avec `with` et pourquoi il fait si peur.

**Comment by dahfazz** [comment]
@Touffy  ...c'est pas *this* ?

**Comment by Touffy** [comment]
> @Touffy ...c'est pas **this** ?

`this` est certes largement incompris par beaucoup de soi-disant développeurs JavaScript, mais non, je parle bien de `with`.

**Comment by olegskl** [comment]
Fait le 30 juillet 2019. Merci !
